### PR TITLE
Add 1D option to ignore 2D functionality

### PR DESCRIPTION
**Pull request by Sosnowsky**
What we discussed in Slack. Please check if it is necessary to add 1d checks in other parts of the code that I might have missed.

### CODE REVIEW

**Comment by Sosnowsky** [comment]
@gregordecristoforo I just made an additional commit now to multiply the array of ones by the free parameter in the blob factories. It is something I need to have a degenerate distribution with value other than 1 (as I can see, there is no other way to do that now)

**Review by gregordecristoforo — APPROVED** [review]

**Comment by gregordecristoforo** [comment]
Seems fine to me, we should also change the test https://github.com/uit-cosmo/2d-propagating-blobs/blob/main/tests/test_analytical.py which isn't adapted to the 1D option yet. I can take a look at that tomorrow.

**Comment by Sosnowsky** [comment]
hmm, why should it be changed? I thought it was a 2d test? I added a new analytical test, which is just this one adapted to 1d.

**Comment by gregordecristoforo** [comment]
This test was originally intended as a 1D case. Sorry I missed you already implemented the new test in 1D. Don't mind my previous comment.

**Pull request merged**
